version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=todo_db
      - DB_USER=ishwor
      - DB_PASS=ishwor99
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ishwor
      POSTGRES_PASSWORD: ishwor99
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
