
services:
  app:
    build:
      context: ../
    expose:
      - "8000"
    volumes:
      - ../:/app
      - ./static:/app/static
      - ./media:/app/media
    env_file:
      - ../.env
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    
  db:
    image: postgres:10-alpine
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data:
