services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./static:/app/staticfiles
    env_file:
      - .env
    command: >
        sh -c "gunicorn todowoo.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data: